name: Build nextjs projects
on:
  push:
    branches: ["dev"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: setup bun.js
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.11

      - run: bun install
      - run: bun run build
